<!DOCTYPE html>
<html ng-app="mineskinApp" ng-controller="skinController">
<head>
    <?php
    $userAgent = $_SERVER["HTTP_USER_AGENT"];

    if (preg_match("/(facebookexternalhit|Twitterbot|Pinterest|Google.*snippet|Discordbot|Uptimerobot)/i",$userAgent)) {
        include("default_seo.php");
    }else{
        ?>
        <title ng-bind="head.pageTitle">MineSkin - Custom Skin Generator</title>
        <link id="favicon" rel="shortcut icon" type="image/png" href="{{head.pageIcon || '/favicon.png'}}"/>

        <!-- SEO -->
        <meta name="keywords" content="mineskin,skin,skull,generator,custom,head,skin,minecraft,player,playerhead,skulls,customskull,spigot,bukkit,generator,api,customblocks">
        <meta name="description" content="{{head.pageDescription}}">
        <meta name="author" content="inventivetalent">

        <meta property="og:type" content="website">
        <meta property="og:title" content="{{head.pageTitle || 'MineSkin'}}">
        <meta property="og:image" content="{{head.pageIcon || '/favicon.png'}}">
        <meta property="og:description" content="{{head.pageDescription}}">

        <meta property="twitter:title" content="{{head.pageTitle || 'MineSkin'}}">
        <meta property="twitter:image" content="{{head.pageIcon || '/favicon.png'}}">
        <meta property="twitter:description" content="{{head.pageDescription}}">
        <meta property="twitter:site" content="@MineSkinOrg">
        <meta property="twitter:creator" content="@Inventivtalent">
        <meta property="twitter:card" content="summary">
        <?php
    }
    ?>


    <!-- Style -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
    <link rel="stylesheet" href="https://spiget.org/css/sticky-footer.min.css">

    <meta name=viewport content="width=device-width, initial-scale=1">

    <base href="/">
</head>
<body>

<div class="container">
    <div class="well clearfix">
        <h1 id="mainTitle" class="page-header" style="cursor: pointer;" onclick="window.location='/'">
            MineSkin
            <small>Custom Skin &amp; Skull Generator</small>
        </h1>

        <div id="alerts">
            <script type="text/ng-template" id="alert.html">
                <div ng-transclude></div>
            </script>
            <div uib-alert ng-repeat="alert in alerts" ng-class="'alert-' + (alert.type || 'info')" close="closeAlert($index)" dismiss-on-timeout="{{alert.timeout}}">{{alert.msg}}</div>
        </div>

        <div id="mainContent" ng-view>
            <!-- Main Content -->
        </div>
    </div>
</div>

<footer class="footer" ng-init="refreshStats()">
    <br/>
    <div class="container">
        <div class="pull-left">
            <span title="{{stats.unique}} unique, {{stats.private}} private">{{stats.total}}</span><strong> Skulls generated by </strong><span>{{stats.accounts}}</span><strong> accounts, </strong><span>{{stats.lastDay}}</span><strong> in the past 24 hours | <a href="https://inventivetalent.org/contact/" target="_blank">Donate an account to speed things up!</a></strong>
        </div>

        <div class="pull-right">
            <a href="https://donation.inventivetalent.org/paypal/?item=MineSkin"><img src="https://static.spigotmc.org/img/btn_donate.gif"/></a> | Maintained by <a href="https://inventivetalent.org?ref=MineSkin">inventivetalent</a> | <a href="http://status.mineskin.org/?aff=38996" title="Website Uptime Monitoring"><img
                    src="https://www.statuscake.com/App/button/index.php?Track=oNgPjMzeYP&Days=7&Design=5"/></a>
        </div>
    </div>
</footer>

<script src="https://code.jquery.com/jquery-3.1.0.min.js" integrity="sha256-cCueBR6CsyA4/9szpPfrX3s49M9vUU5BgtiJj06wt/s=" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.min.js" integrity="sha384-V6/dyDFv85/V/Ktq3ez5B80/c9ZY7jV9c/319rqwNOz3h9CIPdd2Eve0UQBYMMr/" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular-route.js" integrity="sha384-k+Qp/8rZxoiiYGVjOBiZwkEp5yv6clgl2EmwNaE1oUMlfmEYgCWazxf4CyxfZiWG" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.0/angular-cookies.min.js" integrity="sha384-4Rqc4WCYcTgQGo7N/eJANj8VFLYiS0J/XRW6ThAPed/9YJmlNO7iD+ZdbeKi1Eqx" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/angular-ui-bootstrap/2.1.1/ui-bootstrap.min.js" integrity="sha384-wdLJc2YyjuluHF3HVyjY3+6XbqHKHmlryPgblRIwxza9hLmxD9YJtWs16lUOIJB0" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/angular-ui-bootstrap/2.1.1/ui-bootstrap-tpls.min.js" integrity="sha384-WtvotrktirgylB2PB0Rmy8GyjqcT3ho9v1cyvjNZYLj8KZC1bsjfE8S4pniiFqyZ" crossorigin="anonymous"></script>
<script src="https://anglibs.github.io/angular-location-update/angular-location-update.min.js" integrity="sha384-jwZhTNLxbFFhAc5v2tYH1/sMFcN13k0/TzlpdIqnf2aAxpzbRJyn1yqt+FiDbJ5C" crossorigin="anonymous"></script>
<script src="https://platform.twitter.com/widgets.js"></script>

<script src="/js/ng-file-upload.min.js"></script>

<?php
echo '<script src="/script.min.js?' . rand() . '"></script>';
?>
</body>
</html>